### ISSUE TITLE
Creaking does not spawn 

### ISSUE THREAD

**Issue by mairondil** [Yasser444o/Skybedrock#22] opened 2024-12-21 02:26 UTC
I cannot get the creaking to spawn. I've cleared the pale garden island of everything except the heart and 2 pale logs in the correct orientation. The heart is lit up like it's activated. I have a 7*7 platform of logs, dirt, and pale moss 6 blocks below the heart, and a handful of other blocks 7 or 8 blocks below the heart and nothing spawns..I have spent 6 non-consecutive nights standing 35 blocks away observing and not a single creaking has spawned. 

In creative mode I placed a creaking heart and 2 pale logs on the exact same island at night and a creaking spawned immediately.

**Comment by Yasser444o** [comment] 2024-12-21 04:19
Duplicate of https://github.com/Yasser444o/Skybedrock/issues/18#issuecomment-2545234951

Thanks for the report, but i am already aware of this issue and have fixed it for the next update. 

You need to break and replace the heart in order for creakings to spawn

If you don't have silk touch, you can obtain resin from the woodlands mansion to craft a new creaking heart.

**Closed** 2024-12-21 04:19 UTC
