### ISSUE TITLE
Behaviour Pack in Multiplayer/Realm not working

### ISSUE THREAD

**Issue by EliFeldi** [Yasser444o/Skybedrock#4] opened 2024-03-17 11:06 UTC
Hey, 
First of all, I just recently found this gem and have to say I grown to be a big fan of your map/modpack!
I decided to play it together with some friends, sadly it seems like the behaviour pack stops working as soon as I upload it on the Realm.
Did I do something wrong/is this fixable or is it not supposed to work in multiplayer?
It says "unknown name pack is missing" in the Realm settings, I'll also drop some screenshots. Zombies dont drop gravel and there are no diamond chicken, that's how I found out haha :D 
Thanks for helping out!
![Screenshot_20240317_120027_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/163730169/73a2fa61-f367-407a-bf66-3ad2f0f2324a)
![Screenshot_20240317_120032_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/163730169/5b77f26b-ec2d-4ca9-bcdd-05a3b21fd8b9)

**Comment by EliFeldi** [comment] 2024-03-17 11:10
Would you be able to upload a behaviour pack separately?

**Comment by EliFeldi** [comment] 2024-03-17 17:50
I managed to copy the behaviour pack folder out of the working single player map in the minecraft folder, then i renamed it to .mcaddon or .mcpack or something and imported it separately into minecraft. Now my realm looks like in the screenshot below, i spawned some chicken and saw the diamond feather thingy, now I kept afk-ing next to the chicken box that I built and it still did'nt collect any diamonds, only more and more eggs. I can't say if I simply didn't wait long enough yet or if it's actually not working, but that's that. 
The zombies still don't drop any gravel and the iron I collected from probably already hundreds of husks is suspiciously low. 
There is alot of stuff that does work tho, like the nice "?" info page in the inventory. I really am not IT-educated enough to understand, what's going on, maybe I did something terribly wrong but for now I can just say that certain functions that would be vital for playing on the map do not work on my Realm. 

I would be very glad for you helping me understand this because I really like your map and the way your mods (should) work!
![Screenshot_20240317_182650_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/163730169/c779a9d2-f06f-4d8a-976d-075e4e2fd7b5)

**Comment by EliFeldi** [comment] 2024-03-18 00:11
The diamond chicken do not work on my realm either. They looked like it and didn't lay eggs for a while, until at some point they started laying eggs and looking normal again without the diamond being dropped :(

**Comment by Yasser444o** [comment] 2024-03-18 09:08
Hello! thank you so much for playing my map and reporting an issue.
Does the behavior pack work correctly in single player?
the quickest way to check is to open the starter chest and look for a book, compass and a biome detector, if they didn't appear that means the the addon is not applied. 
It should work on realms and servers too, although i had some issues with realms in previous versions which i have resolved, it seems to be a recurring issue with every update.
Diamond chickens don't lay eggs and only lay 1 diamond then convert back to a normal chicken, if it starts to lay eggs then it might have laid a diamond and you missed it. 
Are you playing the latest version of the map (1.20.9)?
and can you send a copy of the world you uploaded to the realm? 
the reason why the help button worked is because its part of the resource pack which apparently, realms don't have any issues with.
you said zombie don't drop gravel. But, do husks drop sand? if so, maybe the QoL subpack is not applied.

**Comment by Yasser4440** [comment] 2024-03-18 10:19
OK, i have done some testing and it appears that servers don't support subpacks, so i will separate QoL subpack to its separate addon and update the map, if you have any more details about the issue from what i asked for above send them here but for now i will close this issue.

**Comment by EliFeldi** [comment] 2024-03-18 10:46
Hey, yes, it works perfectly fine, in fact, even when I download a recent backup of my Realm and play it in singleplayer everything works, or i at least assume that because the zombies do drop gravel then.
The biome detector, structure locator and the guidebook were there on the realm aswell and worked as they should i think.
I couldn't miss the diamonds, i was afk next to them being in a little hopper box, i will send a screenshot if it aswell.
I downloaded the map from PMC some days ago so i assume it must be the latest version. My MCPE is on 1.20.71 which must be newest as i cant find any update in Playstore.
I will send you a copy of my realm backup.
Husks drop sand but zombies dont drop gravel.
Isn't husks dropping sand a vanilla minecraft thing?
Thanks for listening me out and helping me make this work!
I cant send you the whole folder in here, how can i send it to you? Do you have an email address i can send it to?


![Screenshot_20240318_103645_Minecraft](https://github.com/Yasser444o/Skybedrock/assets/163730169/1ef2252a-84ec-4421-b5cc-760cb9769475)

**Comment by EliFeldi** [comment] 2024-03-18 10:55
Nevermind, i saw your comment to make it into .zip folder, so here is my realm backup!

[eAv4ZRqQAwA=.zip](https://github.com/Yasser444o/Skybedrock/files/14635067/eAv4ZRqQAwA.zip)

**Comment by Yasser444o** [comment] 2024-03-18 13:05
I did test the chicken thing and they laid a diamond as intended (to clear your confusion, not all chicken are diamond chicken, only the ones with a diamond feather on thier wings are, they take exactly 3 hours to lay their diamond and won't lay any eggs while they have that feather, they lose it right after they lay the diamond.)
About the zombies not dropping gravel, thing, i figured out that realms and servers don't read the applied subpacks and simply ignore them, and because of that all Qol features won't apply. (crafting recipes, mob drops...)
and No husks don't drop sand in vanilla sadly. 
I am getting rid of the subpacks and making QoL into it's own addon for the next update. for now here is an early access QoL addon you can apply to your realm, and it should fix the bug.

**Comment by Yasser4440** [comment] 2024-03-18 13:06
[skybedrock_qol.mcpack.zip](https://github.com/Yasser444o/Skybedrock/files/14636572/skybedrock_qol.mcpack.zip)

**Comment by EliFeldi** [comment] 2024-03-18 15:07
Thank you so much for the separate QoL.mcpack, I had to make a backup of the realm that I upload with the new separate preinstalled QoL pack, but now it seems to work, the zombies drop gravel and I hope i will get some chicken diamond soon.
I put only diamond chicken in that hopper box that I've sent a screenshot of earlier before, I afk-ed for hours next to it only for them to turn into normal chicken and producing eggs after a while without any diamonds in the chest. Now I have a diamond chicken trapped in it again to test if it works with the changes.
What are the rules for those 3 hours, does the chunk of the chicken have to be loaded the whole time? I built the chicken platform at birch platform (yes, I was stupid to get rid of all grass blocks at 0|0) and my mobgrinder is at the desert, so I'd like to know how I can get to my diamonds fast without losing too much time afk-ing. Would a bed as respawn point next to chicken work? Idk my knowledge of Minecraft is quite old and not pretty big but I remember somewhen having heard something about the chunk of the respawn bed always being loaded.
Thank you so much man, I really enjoy this map and am glad that your responses are so quick and helpful. I mean I don't know anything about you but I bet there is also other stuff you have to do in life so, all I mean to say is: your work is awesome, keep it up, I could imagine this map/mod becoming very popular! 
Are you planning to add more stuff in the future?

**Comment by Yasser444o** [comment] 2024-03-18 22:58
You are so welcome, comments like these are what keeps me going.
I didn't really test if unloading the chicken will restart the timer, but i think it shouldn't, and hopefully it doesn't. Nice world by the way, i think your quad cobblestone generator and double layer mob farm in the desert are pretty clever. i really enjoy it when people understand the beauty of Skyblock and come up with new ways to farm resources. beds don't load chunks, that's probably a myth. thanks again for playing the map and i hope you get your diamond soon, if you don't know there is another way to obtain diamonds, i will give a hint: (pyramid)


a second hint: ||use the wiki||

**Comment by Yasser444o** [comment] 2024-03-18 23:31
What do you think i should add to the map in the future? 
Almost every item, mob, block, biome, and structure is in the map, i would love to hear your suggestion.

**Closed** 2024-03-18 23:41 UTC
