### ISSUE TITLE
Respawning after Dying in the end is all wonky

### ISSUE THREAD

**Issue by Beelover20** [Yasser444o/Skybedrock#19] opened 2024-12-15 16:26 UTC
When you die in the end for whatever reason and you respawn you enter a void, that's registered as the end, but it behaves like the overworld, and once you take void damage, the player spins like crazy (it's really noticeable in the rain), and you have to either die or relog

**Comment by Yasser444o** [comment] 2024-12-16 10:58
I failed to reproduce this bug, i might need more details or a video evidence, when I die in the end dimension (falling to the void, getting killed by a mob, dragon breath, or fall damage) i can respawn normally and nothing weird happens.

**Comment by Beelover20** [comment] 2024-12-17 06:53
Huh, that's weird

**Comment by Yasser444o** [comment] 2024-12-22 16:47
Regardless of the reason, it should be fixed in the next update, because i am removing the end border, so i will mark this one as fixed.

**Closed by Yasser444o** 2024-12-22 16:47 UTC
